name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
    - main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml
  
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

 # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PWD }}


      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./simple-api
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-docker/simple-api
          push: ${{ github.ref == 'refs/heads/main' }}


      - name: Build image and push database
          # DO the same for database
        uses: docker/build-push-action@v3
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./database
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-docker/database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        # DO the same for httpd
        uses: docker/build-push-action@v3
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./httpd
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-docker/httpd
          push: ${{ github.ref == 'refs/heads/main' }}

